#! /usr/bin/env ruby

Dir['./lib/*.rb'].each{ |f| require f }

ERRORS = [LaserMaze::FileLoadError, LaserMaze::ZeroDimensionMazeError]

begin
  LaserMaze::Program.new.run
rescue *ERRORS => e
  puts e.message
end
